# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: devpass
    networks:
      - dbnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 5000:5000
      depends_on:
        - db
      networks:
        - dbnet

networks:
  dbnet:
    driver: bridge
