"""Create task tables

Revision ID: 096a5d18f335
Revises: 
Create Date: 2023-07-17 13:49:17.430154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096a5d18f335'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_task_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opaque_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('retired_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'task_type', name='_owner_task_uc')
    )
    with op.batch_alter_table('owner_task_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_task_association_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_owner_task_association_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_owner_task_association_opaque_id'), ['opaque_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_owner_task_association_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_owner_task_association_retired_at'), ['retired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_owner_task_association_task_type'), ['task_type'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opaque_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at', name='pk_task_id_created_at')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('idx_task_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_opaque_id'), ['opaque_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_opaque_id'))
        batch_op.drop_index(batch_op.f('ix_task_created_by'))
        batch_op.drop_index('idx_task_created_at')

    op.drop_table('task')
    with op.batch_alter_table('owner_task_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_task_association_task_type'))
        batch_op.drop_index(batch_op.f('ix_owner_task_association_retired_at'))
        batch_op.drop_index(batch_op.f('ix_owner_task_association_owner_id'))
        batch_op.drop_index(batch_op.f('ix_owner_task_association_opaque_id'))
        batch_op.drop_index(batch_op.f('ix_owner_task_association_created_by'))
        batch_op.drop_index(batch_op.f('ix_owner_task_association_created_at'))

    op.drop_table('owner_task_association')
    # ### end Alembic commands ###
