"""Initial Migration

Revision ID: b82dfe227473
Revises: 
Create Date: 2023-05-25 00:47:30.788746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82dfe227473'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opaque_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at', name='pk_task_id_created_at')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('idx_task_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_opaque_id'), ['opaque_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_type'), ['type'], unique=False)

    op.create_table('task_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opaque_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_type_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_type_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_task_type_opaque_id'), ['opaque_id'], unique=False)

    op.execute("SELECT create_hypertable('task', 'created_at')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_type_opaque_id'))
        batch_op.drop_index(batch_op.f('ix_task_type_name'))
        batch_op.drop_index(batch_op.f('ix_task_type_created_by'))

    op.drop_table('task_type')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_opaque_id'))
        batch_op.drop_index(batch_op.f('ix_task_created_by'))
        batch_op.drop_index('idx_task_created_at')

    op.drop_table('task')
    # ### end Alembic commands ###
